// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5b52J7XkK5n0xDLXnT14zk-fhf9Ob9IQ',
    appId: '1:892206735488:web:0b1a9ea2060a71af0f0665',
    messagingSenderId: '892206735488',
    projectId: 'spendee-8e14e',
    authDomain: 'spendee-8e14e.firebaseapp.com',
    storageBucket: 'spendee-8e14e.firebasestorage.app',
    measurementId: 'G-9J9KF1E8J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuXDreXCmR-pugtDQbSA5dVEBhq8BSu0I',
    appId: '1:892206735488:android:0f080a36b36b36200f0665',
    messagingSenderId: '892206735488',
    projectId: 'spendee-8e14e',
    storageBucket: 'spendee-8e14e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuB_8qYv7GYc-idx2poixubL5MgGk2IRM',
    appId: '1:892206735488:ios:37f21e607d3145d50f0665',
    messagingSenderId: '892206735488',
    projectId: 'spendee-8e14e',
    storageBucket: 'spendee-8e14e.firebasestorage.app',
    iosBundleId: 'com.example.spendee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuB_8qYv7GYc-idx2poixubL5MgGk2IRM',
    appId: '1:892206735488:ios:37f21e607d3145d50f0665',
    messagingSenderId: '892206735488',
    projectId: 'spendee-8e14e',
    storageBucket: 'spendee-8e14e.firebasestorage.app',
    iosBundleId: 'com.example.spendee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5b52J7XkK5n0xDLXnT14zk-fhf9Ob9IQ',
    appId: '1:892206735488:web:bd9f167473bd8e930f0665',
    messagingSenderId: '892206735488',
    projectId: 'spendee-8e14e',
    authDomain: 'spendee-8e14e.firebaseapp.com',
    storageBucket: 'spendee-8e14e.firebasestorage.app',
    measurementId: 'G-78KGXPN97N',
  );
}
